language: node_js
node_js:
  - "0.11"
  - "0.10"

services:
  - mongodb

before_install: npm install -g grunt-cli
install: npm install
script: grunt test

notifications:
  hipchat: [Zd4ejvwEck7Gsc9UXhEVaH25BKMjaSzvhguxbWQo]@[Mountain-device]
  email:
    recipients:
      - ryojiosawa@gmail.com
      - allenkrulwich@gmail.com
      - carlgoldberg1236@gmail.com
      - supriya.bhat@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
